### ISSUE TITLE
Packetfence Zen13.1

### ISSUE THREAD

**Issue by Khiljiraheel** [julsemaan/profile#1]
Hello Julsemaan,

i have successfully setup the packetfence Zen 13.1 and perform 802.1x authentication. I am not using DHCP as my enviroment use static IP now the problem is i have perform 802.1x authentication on user-id where as "Automatically register devices" is enable in connection profile. The packetfence node details page not brings the node details like computer name

Problem: how to setup and authentication source in which i can restrict BYOD devices to get register on my network as my current authentication rule is "member of" "is member of" "CN=abc,OU=Depat,OU=Groups,DC=abc,DC=com"

**Comment by julsemaan** [comment]
Hey! This is actually the wrong repo for this and I do not contribute to PacketFence anymore.

The repo you're looking for is this: https://github.com/inverse-inc/packetfence
